export const PROPERTY_TYPE_OPTIONS = [
  "Detached",
  "Semi-Detached",
  "Terraced",
  "Flat",
  "Bungalow",
  "Other",
];
export const PROPERTY_CONSTRUCTION_OPTIONS = ["Standard", "Other"];
export const PROPERTY_TENURE_OPTIONS = ["Leasehold", "Freehold"];
export const JUDGEMENT_OPTIONS = ["Yes", "No"];

const prefix = "PropertyDetails";

export const createPropertyDetailsConfig = (prefix) => [
  {
    type: "text",
    id: `${prefix}.PropertyAddress`,
    label: "Property Address",
    autoComplete: "street-address",
    registerOptions: { required: "Property address is required" },
    classes: "sm:col-span-8",
  },
  {
    type: "text",
    id: `${prefix}.Postcode`,
    label: "Postcode",
    autoComplete: "postal-code",
    registerOptions: { required: "Postcode is required" },
    classes: "sm:col-span-4",
  },
  {
    type: "select",
    id: `${prefix}.PropertyType`,
    label: "Property Type",
    autoComplete: "",
    options: PROPERTY_TYPE_OPTIONS,
    registerOptions: { required: "Property type is required" },
    classes: "sm:col-span-4",
  },
  {
    type: "number",
    id: `${prefix}.PropertyValue`,
    label: "Property Value £",
    autoComplete: "",
    registerOptions: { required: "Property value is required" },
    classes: "sm:col-span-4",
  },
  {
    type: "number",
    id: `${prefix}.RentalIncome`,
    label: "Rental Income £",
    autoComplete: "",
    registerOptions: { required: "Rental income is required" },
    classes: "sm:col-span-4",
  },
  {
    type: "number",
    id: `${prefix}.LoanAmountRequired`,
    label: "Loan Amount Required £",
    autoComplete: "",
    registerOptions: { required: "Loan amount required is required" },
    classes: "sm:col-span-4",
  },
  {
    type: "checkbox",
    id: `${prefix}.AddFeesToLoan`,
    label: "Add Fees to Loan?",
    autoComplete: "",
    registerOptions: {},
    classes: "sm:col-span-4",
  },
  {
    type: "text",
    id: `${prefix}.SourceOfDeposit`,
    label: "Source of Deposit (If applicable)",
    autoComplete: "",
    registerOptions: {},
    classes: "sm:col-span-4",
  },
  {
    type: "text",
    id: `${prefix}.NameOfVendor`,
    label: "Name of Vendor",
    autoComplete: "",
    registerOptions: {},
    classes: "sm:col-span-4",
  },
  {
    type: "number",
    id: `${prefix}.TermOfMortgage`,
    label: "Term of Mortgage Required (years)",
    autoComplete: "",
    registerOptions: { required: "Term of mortgage required is required" },
    classes: "sm:col-span-4",
  },
  {
    type: "date",
    id: `${prefix}.YearOfBuild`,
    label: "Year of Build",
    autoComplete: "",
    registerOptions: { required: "Year of build is required" },
    classes: "sm:col-span-4",
  },
  {
    type: "text",
    id: `${prefix}.InitialRatePeriod`,
    label: "Initial Rate Period",
    autoComplete: "",
    registerOptions: { required: "Initial rate period is required" },
    classes: "sm:col-span-4",
  },
  {
    type: "text",
    id: `${prefix}.FixedOtherDetails`,
    label: "Fixed/Other Details",
    autoComplete: "",
    registerOptions: {},
    classes: "sm:col-span-4",
  },
  {
    type: "text",
    id: `${prefix}.DetailsOfSolicitor`,
    label: "Details of Solicitor",
    autoComplete: "",
    registerOptions: { required: "Details of solicitor are required" },
    classes: "sm:col-span-8",
  },
  {
    type: "text",
    id: `${prefix}.ContactForValuationName`,
    label: "Contact for Valuation - Name",
    autoComplete: "",
    registerOptions: { required: "Contact name for valuation is required" },
    classes: "sm:col-span-4",
  },
  {
    type: "text",
    id: `${prefix}.ContactForValuationNumber`,
    label: "Contact for Valuation - Number",
    autoComplete: "",
    registerOptions: { required: "Contact number for valuation is required" },
    classes: "sm:col-span-4",
  },
  {
    type: "email",
    id: `${prefix}.ContactForValuationEmail`,
    label: "Contact for Valuation - Email",
    autoComplete: "",
    registerOptions: { required: "Contact email for valuation is required" },
    classes: "sm:col-span-4",
  },
  {
    type: "select",
    id: `${prefix}.PropertyConstruction`,
    label: "Property Construction",
    autoComplete: "",
    options: PROPERTY_CONSTRUCTION_OPTIONS,
    registerOptions: { required: "Property construction is required" },
    classes: "sm:col-span-4",
  },
  {
    type: "text",
    id: `${prefix}.DirectDebitAccountName`,
    label: "Direct Debit Account Name",
    autoComplete: "",
    registerOptions: { required: "Direct debit account name is required" },
    classes: "sm:col-span-4",
  },
  {
    type: "text",
    id: `${prefix}.DirectDebitAccountNumber`,
    label: "Direct Debit Account Number",
    autoComplete: "",
    registerOptions: { required: "Direct debit account number is required" },
    classes: "sm:col-span-4",
  },
  {
    type: "text",
    id: `${prefix}.DirectDebitSortCode`,
    label: "Direct Debit Sort Code",
    autoComplete: "",
    registerOptions: { required: "Direct debit sort code is required" },
    classes: "sm:col-span-4",
  },
  {
    type: "text",
    id: `${prefix}.DetailsOfProperty`,
    label: "Details of Property (e.g., No of Bedrooms/Units/Flat Floor)",
    autoComplete: "",
    registerOptions: { required: "Details of property are required" },
    classes: "sm:col-span-8",
  },
  {
    type: "select",
    id: `${prefix}.PropertyTenure`,
    label: "Leasehold/Freehold",
    autoComplete: "",
    options: PROPERTY_TENURE_OPTIONS,
    registerOptions: { required: "Property tenure is required" },
    classes: "sm:col-span-4",
  },
  {
    type: "select",
    id: `${prefix}.Judgements`,
    label:
      "Have you had any Judgements, Defaults, Bankruptcies or had any accounts in arrears?",
    autoComplete: "",
    options: JUDGEMENT_OPTIONS,
    registerOptions: { required: "This field is required" },
    classes: "sm:col-span-8",
  },
  {
    type: "select",
    id: `${prefix}.PaymentDifficulties`,
    label:
      "Have you ever failed, or are you experiencing, payment difficulties in keeping up your payments under any previous or current mortgage, rental or loan agreements?",
    autoComplete: "",
    options: JUDGEMENT_OPTIONS,
    registerOptions: { required: "This field is required" },
    classes: "sm:col-span-8",
  },
];

export default createPropertyDetailsConfig;
